apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerter
  template:
    metadata:
      labels:
        app: alerter
    spec:
      imagePullSecrets:
      - name: coscale-registry
      containers:
      - name: alerter
        image: ${REGISTRY}/coscale/alerter:${VERSION}
