apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
      - name: coscale-registry
      containers:
      - name: api
        image: ${REGISTRY}/coscale/api:${VERSION}
        ports:
        - containerPort: 80
