apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      imagePullSecrets:
      - name: coscale-registry
      containers:
      - name: memcached
        image: ${REGISTRY}/coscale/memcached:${VERSION}
        ports:
        - containerPort: 11211
